version: 1.0
deploy:
  # comment in one of the following lines to force the use of the recurring or bootstrap configuration
  #  force: recurring
  force: bootstrap

  # configure the initial deployment of each branch
  bootstrap:
    # directories that are not overwritten or removed by the next deployment
    #excludes:

    # commands that are executed on the runtime after new files are copied
    post-deployment-remote-commands:
      # set right file permissions for Laravel
      - vendor/bin/typo3cms install:setup

  # configure all following deployments of each branch
  #recurring:
    # directories that are not overwritten or removed by the next deployment
    #excludes:

    # commands that are executed on the runtime before new files are copied
    #pre-deployment-remote-commands:

    # commands that are executed on the runtime after new files are copied
    #post-deployment-remote-commands:
